#!/usr/bin/perl
#
# ------------------------------------------------------------------------------------------------------------------------
#
#                                * micmap *
#      Mapping of short reads in fastq format onto a reference
#
#
#  Copyright (C) SIB  - Swiss Institute of Bioinformatics,  2015-2019 Nicolas Guex, Thierry Schuepbach and Christian Iseli
#  Copyright (C) UNIL - University of Lausanne, Switzerland      2019 Nicolas Guex and Christian Iseli
#
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 2 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <https://www.gnu.org/licenses/>.
#
#
#      Code:       Nicolas Guex, Thierry Schuepbach and Christian Iseli
#      Contacts:   Nicolas.Guex@unil.ch and Christian.Iseli@unil.ch
#      Repository: https://github.com/sib-swiss/micmap
#
# ------------------------------------------------------------------------------------------------------------------------
#
use strict;
use warnings;
while ( <> ) {
  my ($cnt, $seq) = $_ =~ /^\s*(\d+)\s+(\w+)\s*$/s;
  die "Bad line $_" unless defined $seq;
  my $revSeq = reverse $seq;
  $revSeq =~ tr/ACGT/TGCA/;
  if ($revSeq lt $seq) {
    print STDERR "$revSeq $cnt\n";
  } else {
    print "$seq $cnt\n";
  }
}
exit 0;
__END__
 188097 AAAAAAAAAAAAAAAAAAAA
   9710 AAAAAAAAAAAAAAAAAAAC
   7846 AAAAAAAAAAAAAAAAAAAG
  10147 AAAAAAAAAAAAAAAAAAAT
