#!/usr/bin/perl
#
# ------------------------------------------------------------------------------------------------------------------------
#
#                                * micmap *
#      Mapping of short reads in fastq format onto a reference
#
#
#  Copyright (C) UNIL - University of Lausanne, Switzerland                 2020  Nicolas Guex
#  Copyright (C) EPFL - Ecole Polytechnique Fédérale Lausanne, Switzerland  2020  Christian Iseli
#
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 2 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <https://www.gnu.org/licenses/>.
#
#
#      Code:       Christian Iseli
#      Contacts:   Nicolas.Guex@unil.ch and Christian.Iseli@unil.ch
#      Repository: https://github.com/sib-swiss/micmap
#
# ------------------------------------------------------------------------------------------------------------------------
#
use strict;
use warnings;
local *FD;
my $sel = shift @ARGV;
my $padding = shift @ARGV;
my $n1 = shift @ARGV;
my %C;
open FD, $sel or die "Can't open $sel : $!";
while ( <FD> ) {
  next if /^#/;
  s/\s+$//s;
  my @F = split /\t/;
  die if $#F < 2;
  my ($chr, $p1, $p2) = @F[0,1,2];
  $chr =~ s/^chr//;
  $p1 -= $padding;
  $p1 = 1 if $p1 < 1;
  $p2 += $padding;
  $C{$chr} = [] unless defined $C{$chr};
  my $A = $C{$chr};
  for my $i ($p1 .. $p2) {
    $$A[$i] = 1;
  }
}
close FD;
my $header = "";
for my $c (1 .. 24) {
  my $fn = $n1 . "_chr" . $c . ".vcf";
  next unless -s $fn;
  open FD, $fn or die "Can't open $fn : $!";
  while ( <FD> ) {
    last unless /^#/;
    if (/^##SAMPLE=</) {
      s/,SEL=[^,>]+/,SEL=$sel/;
      $header .= $_;
    }
  }
  close FD;
}
for my $c (1 .. 24) {
  my $fn = $n1 . "_chr" . $c . ".vcf";
  next unless -s $fn;
  open FD, $fn or die "Can't open $fn : $!";
  while ( <FD> ) {
    if (/^#/) {
      next unless defined $header;
      print;
      print $header;
      undef $header;
      $_ = <FD>;
      while (/^##SAMPLE=</) {
	$_ = <FD>;
      }
      while (/^#/) {
	print;
	$_ = <FD>;
      }
    }
    my @F = split /\t/;
    my $chr = $F[0];
    $chr =~ s/^chr//;
    next unless defined $C{$chr};
    my $A = $C{$chr};
    if (defined $$A[$F[1]]) {
      s/\t\.\tPASS\t\.\t/\t.\tgermline\t.\t/;
      print;
    }
  }
  close FD;
}
exit 0;
__END__
==> /scratch/chris/LD/xgen-exome-research-panel-v2-targets-hg38.bed <==
chr1	69090	70008	OR4F5_1	0	+
chr1	450739	451678	OR4F29_1	0	-
chr1	685715	686654	OR4F16_1	0	-
chr1	925941	926013	SAMD11_1	0	+
chr1	930154	930336	SAMD11_2	0	+
chr1	931038	931089	SAMD11_3	0	+
chr1	935771	935896	SAMD11_4	0	+
chr1	939039	939129	SAMD11_5	0	+
chr1	939274	939460	SAMD11_6	0	+
chr1	941143	941306	SAMD11_7	0	+

==> /tmp/toto/FFPE483_vs_TIL483_old_chr1.vcf <==
##fileformat=VCFv4.1
##SAMPLE=<ID=TIL483,CONTIG=chr1,IQR25=101,MEDIAN=148,IQR75=203,CNT=3411329,SEL=/dev/fd/63>
##SAMPLE=<ID=FFPE483,CONTIG=chr1,IQR25=41,MEDIAN=55,IQR75=73,CNT=3382724,SEL=/dev/fd/63>
##SAMPLE=<ID=TIL483,CONTIG=chr1,IQR25=1,MEDIAN=4,IQR75=42,CNT=31731157>
##SAMPLE=<ID=FFPE483,CONTIG=chr1,IQR25=2,MEDIAN=13,IQR75=43,CNT=14069731>
##FORMAT=<ID=DP,Number=1,Type=Integer,Description="Total read depth">
##FORMAT=<ID=GT,Number=1,Type=String,Description="Genotype">
##FORMAT=<ID=AD,Number=R,Type=Integer,Description="Per-sample read depths for each allele">
##INFO=<ID=varType,Number=1,Type=String,Description="Type of variant">
##contig=<ID=chr1,length=248956422,assembly=b38>
##contig=<ID=chr2,length=242193529,assembly=b38>
##contig=<ID=chr3,length=198295559,assembly=b38>
##contig=<ID=chr4,length=190214555,assembly=b38>
##contig=<ID=chr5,length=181538259,assembly=b38>
##contig=<ID=chr6,length=170805979,assembly=b38>
##contig=<ID=chr7,length=159345973,assembly=b38>
##contig=<ID=chr8,length=145138636,assembly=b38>
##contig=<ID=chr9,length=138394717,assembly=b38>
##contig=<ID=chr10,length=133797422,assembly=b38>
##contig=<ID=chr11,length=135086622,assembly=b38>
##contig=<ID=chr12,length=133275309,assembly=b38>
##contig=<ID=chr13,length=114364328,assembly=b38>
##contig=<ID=chr14,length=107043718,assembly=b38>
##contig=<ID=chr15,length=101991189,assembly=b38>
##contig=<ID=chr16,length=90338345,assembly=b38>
##contig=<ID=chr17,length=83257441,assembly=b38>
##contig=<ID=chr18,length=80373285,assembly=b38>
##contig=<ID=chr19,length=58617616,assembly=b38>
##contig=<ID=chr20,length=64444167,assembly=b38>
##contig=<ID=chr21,length=46709983,assembly=b38>
##contig=<ID=chr22,length=50818468,assembly=b38>
##contig=<ID=chrX,length=156040895,assembly=b38>
##contig=<ID=chrY,length=57227415,assembly=b38>
##contig=<ID=chrM,length=16569,assembly=b38>
##contig=<ID=chrRd,length=7042000,assembly=b38>
##contig=<ID=chrUn,length=4677000,assembly=b38>
##contig=<ID=chrEBV,length=171823,assembly=b38>
##phasing=none
##source=SelectVariants
##variants_justified=left
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	TIL483	FFPE483
chr1	13079	.	C	G	.	PASS	.	GT:DP:AD	0/1:22:19,3	0/0:0:0,0
chr1	14907	.	A	G	.	PASS	.	GT:DP:AD	0/1:24:20,4	0/0:0:0,0
chr1	137825	.	G	A	.	PASS	.	GT:DP:AD	0/1:163:132,31	0/1:26:22,4
chr1	138156	.	G	T	.	PASS	.	GT:DP:AD	0/1:68:39,29	0/0:2:2,0
chr1	139393	.	G	T	.	PASS	.	GT:DP:AD	0/1:510:389,121	0/1:93:70,23
chr1	139405	.	C	A	.	PASS	SOMATIC	GT:DP:AD	0/0:545:545,0	0/1:112:109,3
chr1	139781	.	G	A	.	PASS	.	GT:DP:AD	0/1:55:28,27	0/0:0:0,0
chr1	183629	.	G	A	.	PASS	.	GT:DP:AD	0/1:58:53,5	0/0:3:3,0
chr1	183662	.	G	C	.	PASS	.	GT:DP:AD	0/1:35:30,5	0/0:0:0,0
chr1	185194	.	G	C	.	PASS	.	GT:DP:AD	0/1:68:43,25	0/0:2:0,2
chr1	185262	.	C	A	.	PASS	.	GT:DP:AD	0/1:73:66,7	0/0:2:2,0
chr1	185428	.	A	G	.	PASS	.	GT:DP:AD	0/1:61:28,33	0/0:2:0,2
chr1	185451	.	A	G	.	PASS	.	GT:DP:AD	0/1:69:32,37	0/0:2:0,2

==> /tmp/toto/FFPE483_vs_TIL483_old_chr2.vcf <==
##fileformat=VCFv4.1
##SAMPLE=<ID=TIL483,CONTIG=chr2,IQR25=93,MEDIAN=136,IQR75=191,CNT=2480050,SEL=/dev/fd/63>
##SAMPLE=<ID=FFPE483,CONTIG=chr2,IQR25=40,MEDIAN=55,IQR75=72,CNT=2453423,SEL=/dev/fd/63>
##SAMPLE=<ID=TIL483,CONTIG=chr2,IQR25=1,MEDIAN=2,IQR75=29,CNT=26124810>
##SAMPLE=<ID=FFPE483,CONTIG=chr2,IQR25=1,MEDIAN=10,IQR75=40,CNT=10852194>
##FORMAT=<ID=DP,Number=1,Type=Integer,Description="Total read depth">
##FORMAT=<ID=GT,Number=1,Type=String,Description="Genotype">
##FORMAT=<ID=AD,Number=R,Type=Integer,Description="Per-sample read depths for each allele">
##INFO=<ID=varType,Number=1,Type=String,Description="Type of variant">
##contig=<ID=chr1,length=248956422,assembly=b38>
##contig=<ID=chr2,length=242193529,assembly=b38>
##contig=<ID=chr3,length=198295559,assembly=b38>
##contig=<ID=chr4,length=190214555,assembly=b38>
##contig=<ID=chr5,length=181538259,assembly=b38>
##contig=<ID=chr6,length=170805979,assembly=b38>
##contig=<ID=chr7,length=159345973,assembly=b38>
##contig=<ID=chr8,length=145138636,assembly=b38>
##contig=<ID=chr9,length=138394717,assembly=b38>
##contig=<ID=chr10,length=133797422,assembly=b38>
##contig=<ID=chr11,length=135086622,assembly=b38>
##contig=<ID=chr12,length=133275309,assembly=b38>
##contig=<ID=chr13,length=114364328,assembly=b38>
##contig=<ID=chr14,length=107043718,assembly=b38>
##contig=<ID=chr15,length=101991189,assembly=b38>
##contig=<ID=chr16,length=90338345,assembly=b38>
##contig=<ID=chr17,length=83257441,assembly=b38>
##contig=<ID=chr18,length=80373285,assembly=b38>
##contig=<ID=chr19,length=58617616,assembly=b38>
##contig=<ID=chr20,length=64444167,assembly=b38>
##contig=<ID=chr21,length=46709983,assembly=b38>
##contig=<ID=chr22,length=50818468,assembly=b38>
##contig=<ID=chrX,length=156040895,assembly=b38>
##contig=<ID=chrY,length=57227415,assembly=b38>
##contig=<ID=chrM,length=16569,assembly=b38>
##contig=<ID=chrRd,length=7042000,assembly=b38>
##contig=<ID=chrUn,length=4677000,assembly=b38>
##contig=<ID=chrEBV,length=171823,assembly=b38>
##phasing=none
##source=SelectVariants
##variants_justified=left
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	TIL483	FFPE483
chr2	41366	.	C	T	.	PASS	.	GT:DP:AD	0/1:19:8,11	0/0:0:0,0
chr2	45895	.	A	G	.	PASS	.	GT:DP:AD	1/1:17:0,17	1/1:4:0,4
chr2	233416	.	G	A	.	PASS	.	GT:DP:AD	0/1:13:8,5	0/0:0:0,0
chr2	264895	.	G	C	.	PASS	.	GT:DP:AD	1/1:9:0,9	1/1:7:0,7
chr2	271995	.	T	A	.	PASS	.	GT:DP:AD	0/0:40:39,1	0/1:18:15,3
chr2	271997	.	G	T	.	PASS	.	GT:DP:AD	0/0:38:37,1	0/1:16:13,3
chr2	271998	.	C	G	.	PASS	.	GT:DP:AD	0/0:37:36,1	0/1:14:11,3
chr2	271998	.	CAA	C,CA	.	PASS	.	GT:DP:AD	0/2:39:19,7,13	0/1:13:7,3,3
chr2	271999	.	A	C	.	PASS	.	GT:DP:AD	0/0:20:19,1	0/1:10:7,3
chr2	276908	.	C	G	.	PASS	.	GT:DP:AD	0/1:19:11,8	1/1:3:0,3
chr2	283179	.	C	T	.	PASS	SOMATIC	GT:DP:AD	0/0:137:137,0	0/1:63:60,3
