#!/usr/bin/perl
# $Id$
use strict;
use warnings;
my %buf;
while ( <> ) {
  my ($name,$part) = $_ =~ /^(\S+)\/([12])\s+/;
  die "Bad header $_" unless defined $name;
  $_ .= <>;
  $_ .= <>;
  $_ .= <>;
  if (defined $buf{$name}) {
    if ($part == 1) {
      print STDOUT $_;
      print STDERR $buf{$name};
    } else {
      print STDERR $_;
      print STDOUT $buf{$name};
    }
    delete $buf{$name};
  } else {
    $buf{$name} = $_;
  }
}
my @K = keys %buf;
my $rest = $#K + 1;
die "should be empty but contains $rest" if $rest != 0;
exit 0;
__END__
@HS2000-920_237:8:2304:8924:29561/2
TAACCCTACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTA
+
CCCFFFFFHHHHHIJJJFIIJIJJJJJJIGHIJJJGIGIHI?;D>BDG@FFH@FEBEHCHAE2?DDDBACEEC=;?CB=B?C<<9A59<88A########
@HS2000-920_237:6:2106:19319:19111/2
TAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTCAC
+
CCCFFFFFGHHHHJFIJJJIJGIIJIJJJJIEBDCFHDFHIJCDDBGIHGFGHIEFEECG=?A(;B@??;;?6=;==??#####################
