SET (CPACK_PACKAGE_NAME MicMap)
SET (CPACK_PACKAGE_CONTACT "Thierry Schuepbach")
SET (CPACK_PACKAGE_VENDOR "SIB Swiss Institute of Bioinformatics")
SET (CPACK_PACKAGE_VERSION "${MAJOR_VERSION}.${MINOR_VERSION}.${PATCH_VERSION}")
SET (CPACK_PACKAGE_VERSION_MAJOR   ${MAJOR_VERSION})
SET (CPACK_PACKAGE_VERSION_MINOR  ${MINOR_VERSION})
SET (CPACK_PACKAGE_VERSION_PATCH  ${PATCH-VERSION})
SET (CPACK_PACKAGE_FILE_NAME "${CPACK_PACKAGE_NAME}-${CPACK_PACKAGE_VERSION}-${CMAKE_BUILD_TYPE}-${CMAKE_SYSTEM_NAME}-${CMAKE_SYSTEM_PROCESSOR}")
SET (CPACK_PACKAGE_INSTALL_DIRECTORY "${CPACK_PACKAGE_NAME}/${CPACK_PACKAGE_VERSION}/${CMAKE_BUILD_TYPE}")
SET (CPACK_INCLUDE_TOPLEVEL_DIRECTORY 1)
SET (CPACK_MONOLITHIC_INSTALL TRUE)

IF(UNIX AND NOT WIN32)
	SET (CPACK_GENERATOR "TBZ2")
	SET (CPACK_DEB_COMPONENT_INSTALL ON)
	INSTALL(FILES "${CMAKE_CURRENT_SOURCE_DIR}/License.txt" DESTINATION .
	        PERMISSIONS OWNER_READ GROUP_READ WORLD_READ
	        COMPONENT Applications)
							
ELSE(UNIX AND NOT WIN32)
	#SET (CPACK_COMPONENTS_ALL_IN_ONE_PACKAGE TRUE)
ENDIF(UNIX AND NOT WIN32)

INCLUDE(CPack)
