macro(summary)
STRING(TOUPPER "${CMAKE_BUILD_TYPE}" buildtype)
IF (CMAKE_C_FLAGS)
  SET(cfsp " ")
ENDIF(CMAKE_C_FLAGS)
IF (CMAKE_CXX_FLAGS)
  SET(cxxfsp " ")
ENDIF(CMAKE_CXX_FLAGS)
MESSAGE(STATUS "")
MESSAGE(STATUS "GTL Software Suite configuration summary:")
MESSAGE(STATUS "")
MESSAGE(STATUS "  System name ......................: ${CMAKE_SYSTEM_NAME}")
MESSAGE(STATUS "  Build type .......................: ${CMAKE_BUILD_TYPE}")
MESSAGE(STATUS "")
MESSAGE(STATUS "")
MESSAGE(STATUS "  Install prefix .................. : ${CMAKE_INSTALL_PREFIX}")
MESSAGE(STATUS "  C compiler ...................... : ${CMAKE_C_COMPILER}")
MESSAGE(STATUS "  C++ compiler .................... : ${CMAKE_CXX_COMPILER}")
MESSAGE(STATUS "  C compiler flags ................ : ${CMAKE_C_FLAGS}${cfsp}${CMAKE_C_FLAGS_${buildtype}}")
MESSAGE(STATUS "  C++ compiler flags .............. : ${CMAKE_CXX_FLAGS}${cxxfsp}${CMAKE_CXX_FLAGS_${buildtype}}")
MESSAGE(STATUS "  C compiler SSE2 flag ............ : ${CMAKE_C_SSE2_FLAGS}")
MESSAGE(STATUS "  C compiler SSE 4.1 flag ......... : ${CMAKE_C_SSE41_FLAGS}")
MESSAGE(STATUS "  C compiler AVX flag ..............: ${CMAKE_C_AVX_FLAGS}")
MESSAGE(STATUS "  C compiler AVX 2 flag ............: ${CMAKE_C_AVX2_FLAGS}")
MESSAGE(STATUS "  C compiler AVX512F flag ..........: ${CMAKE_C_AVX512F_FLAGS}")
MESSAGE(STATUS "  C compiler AVX512BW flag .........: ${CMAKE_C_AVX512BW_FLAGS}")
MESSAGE(STATUS "  C compiler AVX512CD flag .........: ${CMAKE_C_AVX512CD_FLAGS}")

MESSAGE(STATUS "")
MESSAGE(STATUS "  Use thread affinity setting ......: ${USE_AFFINITY}")
MESSAGE(STATUS "")
MESSAGE(STATUS "  Build shared libs ............... : ${BUILD_SHARED_LIBS}")
MESSAGE(STATUS "  Build static libs ............... : ${BUILD_STATIC_LIBS}")
MESSAGE(STATUS "  Build static executables ........ : ${STANDALONE}")
MESSAGE(STATUS "")

MESSAGE(STATUS "")


IF(NOT USE_AFFINITY)
  MESSAGE( "!! CPU thread affinity is disabled, hence performance penalty may apply on many-core architecture.")
ENDIF(NOT USE_AFFINITY)

endmacro(summary)
